default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  user: postgres
  password: postgres_password

development:
  <<: *default
  database: boardpackager_library_development

test:
  <<: *default
  database: boardpackager_library_test

production:
  <<: *default
  database: boardpackager_library_production
  password: <%= ENV["BOARDPACKAGER_LIBRARY_DATABASE_PASSWORD"] %>
